spring:
  application:
    name: gvm-finance-be
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

server:
  port: 8080

app:
  frontend-url: ${FRONTEND_URL}

  cors:
    allowed-origins: ${FRONTEND_URL}
    allowed-methods: GET,POST,PUT,DELETE,OPTIONS
    allowed-headers: Content-Type,Authorization
    allow-credentials: true

  jwt:
    secret: ${JWT_SECRET}
    expiration: 600
